

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/virtual-kubelet/virtual-kubelet"
  version = "v0.2-beta-9"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[prune]
  go-tests = true
  unused-packages = true
